export enum ActionType {
  GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST",
  GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS",
  GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE",

  PATCH_USER_DATA_REQUEST = "PATCH_USER_DATA_REQUEST",
  PATCH_USER_DATA_SUCCESS = "PATCH_USER_DATA_SUCCESS",
  PATCH_USER_DATA_FAILURE = "PATCH_USER_DATA_FAILURE",
}
