export enum ActionType {
  USER_DATA_REQUEST = "USER_DATA_REQUEST",
  USER_DATA_SUCCESS = "USER_DATA_SUCCESS",
  USER_DATA_FAILURE = "USER_DATA_FAILURE",

  AVAILABLE_SERVICES_REQUEST = "AVAILABLE_SERVICES_REQUEST",
  AVAILABLE_SERVICES_SUCCESS = "AVAILABLE_SERVICES_SUCCESS",
  AVAILABLE_SERVICES_FAILURE = "AVAILABLE_SERVICES_FAILURE",
}
