export enum ActionType {
  AVAILABLE_SERVICES_REQUEST = "AVAILABLE_SERVICES_REQUEST",
  AVAILABLE_SERVICES_SUCCESS = "AVAILABLE_SERVICES_SUCCESS",
  AVAILABLE_SERVICES_FAILURE = "AVAILABLE_SERVICES_FAILURE",
}
